language: cpp

before_install:
 - sudo add-apt-repository --yes ppa:beineri/opt-qt571-trusty
 - sudo apt-get update -qq
install:
 - sudo apt-get install -qq qt57base

branches:
  only:
    - master
matrix:
  include:
  - compiler: clang
    os: linux
    env: QMAKESPEC=linux-clang
  - compiler: gcc
    os: linux
    env: QMAKESPEC=linux-g++
#  - compiler: clang
#    os: osx
#    env: QMAKESPEC=macx-clang
script:
- source /opt/qt57/bin/qt57-env.sh
- /opt/qt57/bin/qmake -r && make
